esphome:
  name: climatehub

esp8266:
  board: d1

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 3min

ota:
  platform: esphome
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_server

one_wire:
  - platform: gpio
    pin: 2

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    state_topic: esphome/climatehub/version

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 10s
    state_topic: esphome/climatehub/wifi_signal
    retain: false

  - platform: dallas_temp
    name: "DS18B20 Plafond"
    address: 0x89051660b683ff28
    state_topic: sensors/climatehub-plafond/temperature
    retain: false
  - platform: dallas_temp
    name: "DS18B20 Vloer"
    address: 0xf5041664269fff28
    state_topic: sensors/climatehub-vloer/temperature
    retain: false
