esphome:
  name: plafond-co2

esp32:
  board: esp32thing
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

logger:

mqtt:
  broker: !secret mqtt_server

uart:
    id: uart_mhz19
    rx_pin: 22
    tx_pin: 21
    baud_rate: 9600

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    state_topic: bitlair/esphome/plafond-co2/version

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 10s
    state_topic: bitlair/esphome/plafond-co2/wifi_signal
    retain: false

  - platform: mhz19
    uart_id: uart_mhz19
    co2:
      name: "MH-Z19 CO2 Value"
      id: co2
      state_topic: bitlair/climate/plafond/co2_ppm
      retain: false
    update_interval: 10s
    automatic_baseline_calibration: false
