esphome:
  name: spacestate-bitlair

esp32:
  board: esp32thing
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

logger:

mqtt:
  broker: !secret mqtt_server
  discovery: false

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    state_topic: bitlair/esphome/spacestate-bitlair/version

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 10s
    state_topic: bitlair/esphome/spacestate-bitlair/wifi_signal
    retain: false

binary_sensor:
  - platform: gpio
    name: "Bitlair State"
    id: switch_bitlair
    state_topic: bitlair/switch/state/bitlair
    pin:
      number: 5
      mode: INPUT_PULLUP
      inverted: true
